version: "3"
services:
  youtube:
    build: ./
    container_name: youtube
    volumes:
      - ./code:/code
      - ./file:/file
      - /home/mai/Music:/music
    working_dir: /code
    # tty: true
    command: [python3, download.py]